Add development docs
redbrick/blockbot pull request #44
Opened 2024-10-07 11:22 UTC by novanai

Add developer documentation, explaining the different libraries we use and how to understand their individual documentation.

2024-11-11 14:56 UTC, aydenjahola commented on README.md
> -Blockbot is a Discord bot, written in Python, that is maintained by the Redbrick Webgroup. This project uses [`hikari`](https://github.com/hikari-py/hikari/), an opinionated microframework, to interf
I think adding hyperlink to what redbrick webgroup would be useful here

2024-11-11 15:01 UTC, aydenjahola requested changes
I think adding hyperlink to what redbrick webgorup is would be good if someone's viewing repo without knowing what webgroup is

2024-11-11 16:08 UTC, wizzdom submitted a review, later dismissed
Looking good! Cleans things up nicely

2024-11-11 16:21 UTC, HypnoAnt submitted a review, later dismissed
LGTM

2024-11-11 16:21 UTC, aydenjahola submitted a review, later dismissed

2024-11-12 11:07 UTC, aydenjahola approved these changes

2024-11-12 11:24 UTC, merged